#
# Makefile
# zhangyule, 2017-12-15 17:52
#

all:
	@echo "Makefile needs your attention"
	g++ -std=c++11 -o train ./model_main.cc ./poisson_regression.cc -O3 -ltcmalloc

clean:
	rm -rf *.o train

# vim:ft=make
#
